In [ ]:
# Python Project for Data Analytics(Beginners)
# (A part of Big Data Analysis)

# The Weather Dataset
# Description:
# The Weather Dataset is a time-series dataset with per-hour information about the weather condition at a particular location. It records Temperature, dew Point temperature, Relative humidity, Wind speed, Visibility, Pressure and conditions.

# This Dataset available as a csv file. We are going to analyze this dataset using Pandas dataframe.

# Workflow:
# Import library
# Analyzing the data
# solve few questions of Data Analytics



# Pandas documentation: http://pandas.pydata.org/
# 10 minutes to pandas: https://pandas.pydata.org/pandas-docs/stable/10min.html
# Cookbook- Useful Pandas Recipes: https://pandas.pydata.org/pandas-docs/stable/cookbook.html
# Pandas and Python Top 10: http://manishamde.github.io/blog/2013/03/07/pandas-and-python-top-10/

# Pandas Series
# Very similar to a NumPy array.

# What differentiates the NumPy array from a Series, is that a Series can have axis labels, meaning it can be indexed by a label, instead of just a number location.


Pandas Series: 
Very similar to a NumPy array.

What differentiates the NumPy array from a Series, is that a Series can have axis labels, meaning it can be indexed by a label, instead of just a number location.


How to create a Series?
You can convert a list, numpy array, or dictionary to a Series. To create a series you call the function pd.Series(). Let's see an example of the same.

We will create a series from

list
numpy array
dictionary

In [1]:
import pandas as pd

In [ ]:
How to create a Series?
You can convert a list, numpy array, OR  dictionary to a Series. To create a series you call the function pd.Series(). Let's see an example of the same.

We will create a series from

list
numpy array
dictionary

In [1]:
import pandas as pd

In [8]:
#creating a pandas series from a list
import pandas as pd

my_list = [10, 20, 30]
series = pd.Series(my_list)

print(series)
print(series.index)
print(series.values)

0    10
1    20
2    30
dtype: int64
RangeIndex(start=0, stop=3, step=1)
[10 20 30]

In [43]:
# creating a series from numPy Array
# import numpy as np
# import pandas as pd

# index = ['a','b','c']
# arr = np.array([10,20,30])

# pd.Series(data=arr,index=index)


# 2nd i.e=

# array = np.array([8,54,43,6,73,78])
# s = pd.Series(array)
# print(s)
# print(type (s))
 

# # create numpy array using array method
# array = np.array([1.2,5.5,2.9,4.6])
# s = pd.Series(array, index=list('abcd'))
# s

# arr = np.array([1,2,3,4,5,6,7,])
# p = pd.Series(arr, index= list("abcdefg") )
# p


# arr = np.array([1,2,3])
# data= pd.Series(data)
# data

0    1
1    2
2    3
dtype: int64

In [48]:
# creating a series from dictionary
import pandas as pd

d = {'a':10, 'b':20, 'c':30}
pd.Series(d)


my_dict = {'a' : 10, 'b': 20, 'c': 30}
Data = pd.Series(my_dict)

data


my_dict2 = {'name': 'rahul', 'age':10,'class': 'ten' }
carmel = pd.Series(my_dict2)
carmel

a    10
b    20
c    30
dtype: int64

In [77]:
# Using Index in a Series

# The key to using a Series is understanding its index.

# Pandas makes use of these index names or numbers by allowing for fast lookups of information (works like a hash table or dictionary).

# Custom index
import pandas as pd
ser1 = pd.Series([1,2,3,4], index=['USA', 'Germany','USSR', 'Japan']) 
ser2 = pd.Series([1,2,5,4], index=['USA', 'Germany','Italy', 'Japan'])

In [80]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [81]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [88]:
DataFrame Basics

We'll talk about

How to create a DataFrame, the primary data structure in pandas
How to find the shape and rank of the created or existing DataFrames
How to read DataFrames from a file
What are indexes, and how do they work in the domain of Pandas DataFrames

TypeError: 'Series' object is not callable

In [ ]:
What are DataFrames?
DataFrames are a way to store data in rectangular grids that can easily be overviewed. Each row of these grids corresponds to measurements or values of an instance, while each column is a vector containing data for a specific variable. This means that a data frame’s rows do not need to contain, but can contain, the same type of values: they can be numeric, character, logical, etc.
Data frames in Python come within the Pandas library, and they are defined as a two-dimensional labeled data structures with columns of potentially different types.
In general, you could say that the Pandas data frame consists of three main components: the data, the index, and the columns.

Creating DataFrames manually

The function that you will use is the Pandas Dataframe() function: it requires you to pass the data that you want to put in, the indices and the columns.

Remember that the data that is contained within the data frame doesn’t have to be homogenous.

In [109]:
#Creating DataFrames manually
import pandas as pd
import numpy as np

# df = pd.DataFrame([[1, 2, 3],
#                    [3, 4, 5],
#                    [5, 6, 7],
#                    [7, 8, 9]])
# df
# type(df)

df1 = pd.DataFrame([[1,2,3],
                    [3,4,5],
                    [6,7,8],
                    [9,5,3]])

df1
type(df1)

pandas.core.frame.DataFrame

In [146]:
import pandas as pd
df3 = pd.DataFrame([[1, 2, 3], [3, 4, 5], [5, 6, 7], [7, 8, 9]])

print("shape:", df.shape)
print("index:", df.shape)

df3

TypeError: 'Series' object is not callable

In [167]:
# Understanding the Index

# Before you start with adding, deleting and renaming the components of your DataFrame, you first need to know how you can select these elements.

# This is where Indexes come into play, just the way you can use an idex page in a book to locate your chapters, you can use the loc() 
# or iloc() function in pandas to access data in particular columns of your DataFrame.




# df6 = pd.DataFrame([[1, 2, 3], [3, 4, 5], [5, 6, 7], [7, 8, 9]],
#                   index= ['a','b','c','d'], columns=['x','y','z'])

# df6


df7 = pd.DataFrame([[1,2,3,4],[4,5,6,7],[7,8,9,0],[1,2,3,6]],
                   index= ['a','b','c','d'], columns=[0,1,2,3])

df7

   0  1  2  3
a  1  2  3  4
b  4  5  6  7
c  7  8  9  0
d  1  2  3  6

In [282]:
df2 = pd.DataFrame([[1, 2, 3], [3, 4, 5], [5, 6, 7], [7, 8, 9]],
                   index=['a', 'b', 'c', 'd'], columns=['x', 'y', 'z'])

print("Shape:", df.shape)
print("Index:", df.index)

df2

TypeError: 'Series' object is not callable

In [ ]:
The Weather Dataset: Reading DataFrames from Files
The Weather Dataset is a time-series data set with per-hour information about the weather conditions at a particular location. It records Temperature, Dew Point Temperature, Relative Humidity, Wind Speed, Visibility, Pressure, and Conditions.

This data is available as a CSV file. We are going to use Pandas DataFrames and analyse this dataset.

In [283]:
# Read the data into a data frame
weather_df = pd.read_csv('/Users/pradeepsingh/Desktop/Data/weather_2012.csv')
weather_df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [177]:
weather_df['Date/Time'].head()

0    2012-01-01 00:00:00
1    2012-01-01 01:00:00
2    2012-01-01 02:00:00
3    2012-01-01 03:00:00
4    2012-01-01 04:00:00
Name: Date/Time, dtype: object

In [181]:
# Let's convert the Date/Time column datatype from object to timestamp so that we can access the month directly using the attribute dt.month

weather_df['Date/Time'] = pd.to_datetime(weather_df['Date/Time'])
weather_df['Date/Time'].head()

0   2012-01-01 00:00:00
1   2012-01-01 01:00:00
2   2012-01-01 02:00:00
3   2012-01-01 03:00:00
4   2012-01-01 04:00:00
Name: Date/Time, dtype: datetime64[ns]

In [183]:
# How to Analyze DataFrames?
# The following functions help you understand and explore summaries of your data without having to view the whole DataFrame

# Provides a summary of a DataFrame: rows, columns, data types of columns (if automatically detected) and the memory usage.

# For detailed summaries of the the DataFrame, you can pass optional arguments verbose=True and null_counts=True to the .info() method to output information for all of the columns


weather_df.info()
# Bring the cursor inside the brackets of info() and hit shift+tab & see what you get.
 # This will work for any function in Pandas

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date/Time           8784 non-null   datetime64[ns]
 1   Temp (C)            8784 non-null   float64
 2   Dew Point Temp (C)  8784 non-null   float64
 3   Rel Hum (%)         8784 non-null   int64
 4   Wind Spd (km/h)     8784 non-null   int64
 5   Visibility (km)     8784 non-null   float64
 6   Stn Press (kPa)     8784 non-null   float64
 7   Weather             8784 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(2), object(1)
memory usage: 549.1+ KB

In [187]:
# .head()
# It is used to preview a part of a large DataFrame, similar to the linux head command. This reduces time and resources required if whole DataFrame was to be fetched instead. Shows the first N rows in the data (by default, N=5).

weather_df.head(5)
weather_df.head(10)

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog
5,2012-01-01 05:00:00,-1.4,-3.3,87,9,6.4,101.27,Fog
6,2012-01-01 06:00:00,-1.5,-3.1,89,7,6.4,101.29,Fog
7,2012-01-01 07:00:00,-1.4,-3.6,85,7,8.0,101.26,Fog
8,2012-01-01 08:00:00,-1.4,-3.6,85,9,8.0,101.23,Fog
9,2012-01-01 09:00:00,-1.3,-3.1,88,15,4.0,101.20,Fog

In [188]:
# .index
# This attribute provides the index of the dataframe.

# Indexing identifies data using known indicators that allows intuitive getting and setting of subsets of the data set.

# A major advantage of Pandas over NumPy is that each of the columns and rows has a label. Working with column positions is possible, but it can be hard to keep track of which 
# number corresponds to which column.

# We can work with labels using the pandas.DataFrame.loc method, which allows us to index using labels instead of positions.

weather_df.index

RangeIndex(start=0, stop=8784, step=1)

In [290]:
# .unique()
# This method, which belongs to the Series object, can be useful when trying to identify unique values in a column.

# Uniques are returned in order of appearance.
# It is significantly faster than numpy.unique and includes N/A values



weather_df['Weather']

0                        Fog
1                        Fog
2       Freezing Drizzle,Fog
3       Freezing Drizzle,Fog
4                        Fog
                ...
8779                    Snow
8780                    Snow
8781                    Snow
8782                    Snow
8783                    Snow
Name: Weather, Length: 8784, dtype: object

In [288]:
# This method, which belongs to the Series object, can be useful when trying to identify unique values in a column.

# Uniques are returned in order of appearance.
# It is significantly faster than numpy.unique and includes N/A values

weather_df['Weather'].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 'Rain,Snow Grains', 'Rain,Snow,Ice Pellets',
       'Snow Showers,Fog', 'Moderate Snow,Blowing Snow'], dtype=object)

In [196]:
weather_df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [233]:
#Find all the unique Wind Speed values recorded in the dataset

#weather_df['Wind Spd (km/h)'].nunique

#Q.2 Find the number of time when the 'Weather is exactly clear'.¶

# df.head(2)

# #1: value_counts()
df.Weather.value_counts()
weather_df[weather_df == 'Clear']

Series([], Name: Weather, dtype: int64)

In [292]:
# .nunique()

# This method belongs to the Series object and can be useful when trying to identify the number of unique values in a column.

# Excludes NA values by default
# Always returns an integer value

#weather_df.unique
weather_df['Weather'].nunique()

50

In [343]:
# .value_counts()


# This method, which belongs to the Series object, can be useful when trying to identify unique values and their counts in a column

# The resulting object will be in descending order so that the first element is the most frequently-occurring element.
# Excludes NA values by default.


weather_df['Weather'].value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Freezing Fog                                  4
Snow Showers,Fog                              4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Moderate Snow,Blowing Snow                    2
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Thunderstorms,Heavy Rain Showers              1
Freezing Rain,Snow Grains                     1
Name: Weather, dtype: int64

In [347]:
df.head(2)

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog

In [348]:
#1: value_counts()
df.Weather.value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Freezing Fog                                  4
Snow Showers,Fog                              4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Moderate Snow,Blowing Snow                    2
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Thunderstorms,Heavy Rain Showers              1
Freezing Rain,Snow Grains                     1
Name: Weather, dtype: int64

In [349]:
#2. Filtering

df[df.Weather== 'Clear']

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
67,2012-01-03 19:00:00,-16.9,-24.8,50,24,25.0,101.74,Clear
114,2012-01-05 18:00:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,2012-01-05 19:00:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,2012-01-05 20:00:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,2012-01-05 21:00:00,-9.0,-14.8,63,13,25.0,100.83,Clear
...,...,...,...,...,...,...,...,...
8646,2012-12-26 06:00:00,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,2012-12-28 10:00:00,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,2012-12-29 01:00:00,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,2012-12-29 02:00:00,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,2012-12-30 20:00:00,-13.8,-16.5,80,24,25.0,101.52,Clear

In [350]:
#3. groupby()

#df.head()
df.groupby('Weather').get_group('Clear')

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
67,2012-01-03 19:00:00,-16.9,-24.8,50,24,25.0,101.74,Clear
114,2012-01-05 18:00:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,2012-01-05 19:00:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,2012-01-05 20:00:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,2012-01-05 21:00:00,-9.0,-14.8,63,13,25.0,100.83,Clear
...,...,...,...,...,...,...,...,...
8646,2012-12-26 06:00:00,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,2012-12-28 10:00:00,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,2012-12-29 01:00:00,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,2012-12-29 02:00:00,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,2012-12-30 20:00:00,-13.8,-16.5,80,24,25.0,101.52,Clear

In [371]:
#Find the number of time when the 'Weather is exactly 4km/h'.¶
weather_df[weather_df['Wind Spd (km/h)']==4]

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog

In [372]:
weather_df[weather_df['Wind Spd (km/h)']==4].count()

Date/Time             2
Temp (C)              2
Dew Point Temp (C)    2
Rel Hum (%)           2
Wind Spd (km/h)       2
Visibility (km)       2
Stn Press (kPa)       2
Weather               2
dtype: int64

In [373]:
# Find out all the null values in the data.

df.isnull().sum()

Date/Time             0
Temp (C)              0
Dew Point Temp (C)    0
Rel Hum (%)           0
Wind Spd (km/h)       0
Visibility (km)       0
Stn Press (kPa)       0
Weather               0
dtype: int64

In [378]:
df.notnull().sum()
# NO null values are present in this dataset.

Date/Time             8784
Temp (C)              8784
Dew Point Temp (C)    8784
Rel Hum (%)           8784
Wind Spd (km/h)       8784
Visibility (km)       8784
Stn Press (kPa)       8784
Weather               8784
dtype: int64

In [379]:
df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [383]:
# Rename the column name 'Weather ' of the dataframe to 'Weather condition'.

df.rename(columns={'Weather':'Weather Condition'}) # rename Weather column to Weather Condition
df.rename(columns={'Temp (C)':'temprature condition'}) #rename Temp (C) to temprature condition

,Date/Time,temprature condition,Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [384]:
df.head(2)

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog

In [467]:
# In languages like C curly braces ( {} ) are used to create program blocks used in flow control. 
# In Python, curly braces are used to define a data structure called a dictionary (a key/value mapping), 
# while white space indentation is used to define program blocks
df.rename(columns={'Weather':'Weather Condition'},inplace=True) # changd column name permantly

In [387]:
df.head(2)

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather Condition
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog

In [395]:
#What is the mean 'visibility'?.

#df.head(2)
df.mean()

/var/folders/g3/f4jwjvwx1b33wndzh0wy9bcm0000gn/T/ipykernel_9537/1282175685.py:4: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean()

Temp (C)                8.798144
Dew Point Temp (C)      2.555294
Rel Hum (%)            67.431694
Wind Spd (km/h)        14.945469
Visibility (km)        27.664447
Stn Press (kPa)       101.051623
dtype: float64

In [468]:
#What is the standard deviation of 'Pressure ' in this data?¶

#df.head()
df.Press_kPa.std()

AttributeError: 'DataFrame' object has no attribute 'Press_kPa'

In [469]:
#What is the variance of 'Relative Humidity ' in this data?
df['Rel Hum_%'].var() #space between name so using []
#weather_df['Rel Hum_%'].var() #space between name so using []

KeyError: 'Rel Hum_%'

In [473]:
#Find all instances when 'Snow' was recorded.

#1:value_counts()
#df.head()
df['Weather Condition'].value_counts()
df[df['Weather Condition']=='Snow']

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather Condition
55,2012-01-03 07:00:00,-14.0,-19.5,63,19,25.0,100.95,Snow
84,2012-01-04 12:00:00,-13.7,-21.7,51,11,24.1,101.25,Snow
86,2012-01-04 14:00:00,-11.3,-19.0,53,7,19.3,100.97,Snow
87,2012-01-04 15:00:00,-10.2,-16.3,61,11,9.7,100.89,Snow
88,2012-01-04 16:00:00,-9.4,-15.5,61,13,19.3,100.79,Snow
...,...,...,...,...,...,...,...,...
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [474]:
#3: str.contains
df[df['Weather Condition'].str.contains('Snow')]

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather Condition
41,2012-01-02 17:00:00,-2.1,-9.5,57,22,25.0,99.66,Snow Showers
44,2012-01-02 20:00:00,-5.6,-13.4,54,24,25.0,100.07,Snow Showers
45,2012-01-02 21:00:00,-5.8,-12.8,58,26,25.0,100.15,Snow Showers
47,2012-01-02 23:00:00,-7.4,-14.1,59,17,19.3,100.27,Snow Showers
48,2012-01-03 00:00:00,-9.0,-16.0,57,28,25.0,100.35,Snow Showers
...,...,...,...,...,...,...,...,...
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [477]:
df[df['Weather Condition'].str.contains('Snow')].head(50)

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather Condition
41,2012-01-02 17:00:00,-2.1,-9.5,57,22,25.0,99.66,Snow Showers
44,2012-01-02 20:00:00,-5.6,-13.4,54,24,25.0,100.07,Snow Showers
45,2012-01-02 21:00:00,-5.8,-12.8,58,26,25.0,100.15,Snow Showers
47,2012-01-02 23:00:00,-7.4,-14.1,59,17,19.3,100.27,Snow Showers
48,2012-01-03 00:00:00,-9.0,-16.0,57,28,25.0,100.35,Snow Showers
50,2012-01-03 02:00:00,-10.5,-15.8,65,22,12.9,100.53,Snow Showers
51,2012-01-03 03:00:00,-11.3,-18.7,54,33,25.0,100.61,Snow Showers
53,2012-01-03 05:00:00,-12.9,-19.1,60,22,25.0,100.76,Snow Showers
54,2012-01-03 06:00:00,-13.3,-19.3,61,19,25.0,100.85,Snow Showers
55,2012-01-03 07:00:00,-14.0,-19.5,63,19,25.0,100.95,Snow
84,2012-01-04 12:00:00,-13.7,-21.7,51,11,24.1,101.25,Snow
86,2012-01-04 14:00:00,-11.3,-19.0,53,7,19.3,100.97,Snow
87,2012-01-04 15:00:00,-10.2,-16.3,61,11,9.7,100.89,Snow
88,2012-01-04 16:00:00,-9.4,-15.5,61,13,19.3,100.79,Snow
89,2012-01-04 17:00:00,-8.9,-13.2,71,9,4.8,100.76,Snow
90,2012-01-04 18:00:00,-8.9,-12.6,75,11,9.7,100.69,Snow
91,2012-01-04 19:00:00,-8.4,-12.7,71,9,16.1,100.65,Snow
92,2012-01-04 20:00:00,-7.8,-12.1,71,9,16.1,100.61,Snow
93,2012-01-04 21:00:00,-7.6,-11.6,73,7,11.3,100.54,Snow
94,2012-01-04 22:00:00,-9.5,-12.7,77,6,9.7,100.50,Snow
95,2012-01-04 23:00:00,-9.6,-12.6,79,6,9.7,100.42,Snow
96,2012-01-05 00:00:00,-8.8,-11.7,79,4,9.7,100.32,Snow
97,2012-01-05 01:00:00,-7.5,-10.2,81,0,9.7,100.29,Snow
98,2012-01-05 02:00:00,-5.4,-8.3,80,9,8.0,100.28,Snow
99,2012-01-05 03:00:00,-5.0,-7.7,81,11,9.7,100.24,Snow
100,2012-01-05 04:00:00,-4.1,-6.5,83,9,4.8,100.21,Snow
101,2012-01-05 05:00:00,-7.0,-9.5,82,4,4.0,100.19,Snow
102,2012-01-05 06:00:00,-8.2,-10.7,82,6,6.4,100.26,Snow
103,2012-01-05 07:00:00,-7.1,-9.7,82,9,9.7,100.31,Snow
104,2012-01-05 08:00:00,-6.1,-9.1,79,11,9.7,100.39,Snow
123,2012-01-06 03:00:00,-10.6,-16.0,64,0,9.7,100.76,Snow
124,2012-01-06 04:00:00,-11.3,-16.1,68,15,3.2,100.70,Snow
125,2012-01-06 05:00:00,-11.8,-16.0,71,19,2.8,100.61,Snow
126,2012-01-06 06:00:00,-12.0,-16.2,71,22,4.8,100.58,Snow
127,2012-01-06 07:00:00,-14.4,-16.3,85,22,2.4,100.52,Snow
128,2012-01-06 08:00:00,-12.3,-16.2,73,24,11.3,100.51,Snow
129,2012-01-06 09:00:00,-12.5,-16.7,71,26,19.3,100.53,Snow
130,2012-01-06 10:00:00,-12.3,-16.3,72,28,16.1,100.47,Snow
131,2012-01-06 11:00:00,-12.0,-16.0,72,17,24.1,100.36,Snow
132,2012-01-06 12:00:00,-11.7,-15.4,74,28,19.3,100.23,Snow
133,2012-01-06 13:00:00,-11.9,-15.6,74,20,24.1,100.13,Snow
134,2012-01-06 14:00:00,-11.2,-14.8,75,19,19.3,100.07,Snow
135,2012-01-06 15:00:00,-11.5,-14.4,79,19,12.9,100.06,Snow
136,2012-01-06 16:00:00,-11.6,-14.7,78,19,19.3,100.10,Snow
137,2012-01-06 17:00:00,-11.2,-14.3,78,17,25.0,100.15,Snow
158,2012-01-07 14:00:00,-4.4,-6.9,83,6,8.0,100.09,Snow
159,2012-01-07 15:00:00,-3.7,-6.1,83,11,8.0,100.09,Snow
160,2012-01-07 16:00:00,-3.6,-5.9,84,0,8.0,100.15,Snow
161,2012-01-07 17:00:00,-3.1,-5.4,84,13,8.0,100.27,Snow
162,2012-01-07 18:00:00,-3.2,-5.3,85,6,9.7,100.33,Snow

In [478]:
df[df['Weather Condition'].str.contains('Snow')].tail(50)

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather Condition
8680,2012-12-27 16:00:00,-4.5,-6.2,88,37,2.0,100.44,"Snow,Blowing Snow"
8681,2012-12-27 17:00:00,-4.2,-5.9,88,32,3.2,100.47,"Snow,Blowing Snow"
8682,2012-12-27 18:00:00,-4.0,-5.7,88,28,8.0,100.49,"Snow,Blowing Snow"
8683,2012-12-27 19:00:00,-3.9,-5.6,88,26,9.7,100.52,"Snow,Blowing Snow"
8684,2012-12-27 20:00:00,-3.7,-5.3,89,37,16.1,100.58,Snow
8685,2012-12-27 21:00:00,-3.7,-4.8,92,24,4.8,100.62,"Freezing Drizzle,Snow"
8686,2012-12-27 22:00:00,-3.8,-4.6,94,20,4.8,100.65,"Freezing Drizzle,Snow"
8687,2012-12-27 23:00:00,-4.0,-5.6,89,24,9.7,100.70,Snow
8688,2012-12-28 00:00:00,-4.2,-5.7,89,19,8.0,100.78,"Freezing Drizzle,Snow"
8689,2012-12-28 01:00:00,-4.4,-6.6,85,15,6.4,100.83,"Freezing Drizzle,Snow"
8690,2012-12-28 02:00:00,-4.3,-6.3,86,11,12.9,100.93,"Freezing Drizzle,Snow"
8691,2012-12-28 03:00:00,-4.6,-5.9,91,13,4.0,101.01,Snow
8692,2012-12-28 04:00:00,-4.9,-5.9,93,9,9.7,101.00,Snow
8723,2012-12-29 11:00:00,-10.9,-12.2,90,7,6.4,101.09,"Snow Showers,Fog"
8724,2012-12-29 12:00:00,-10.5,-11.6,92,11,8.0,100.93,"Snow Showers,Fog"
8725,2012-12-29 13:00:00,-10.0,-11.1,92,22,9.7,100.63,"Snow Showers,Fog"
8726,2012-12-29 14:00:00,-9.3,-10.5,91,22,4.8,100.60,"Snow,Fog"
8727,2012-12-29 15:00:00,-8.8,-10.0,91,20,1.2,100.55,"Snow,Fog"
8728,2012-12-29 16:00:00,-8.5,-9.9,90,24,1.2,100.49,"Snow,Fog"
8729,2012-12-29 17:00:00,-9.0,-10.4,90,19,2.4,100.46,"Snow,Fog"
8730,2012-12-29 18:00:00,-9.3,-10.9,88,26,6.4,100.38,"Snow,Fog"
8731,2012-12-29 19:00:00,-9.5,-11.2,87,26,3.2,100.33,"Snow,Fog"
8732,2012-12-29 20:00:00,-9.7,-11.6,86,24,9.7,100.25,"Snow,Fog"
8733,2012-12-29 21:00:00,-9.8,-11.8,85,24,8.0,100.24,"Snow,Fog"
8734,2012-12-29 22:00:00,-10.1,-11.6,89,15,2.4,100.20,"Snow,Fog"
8735,2012-12-29 23:00:00,-10.0,-12.0,85,20,6.4,100.19,"Snow,Fog"
8736,2012-12-30 00:00:00,-9.6,-11.3,87,13,3.2,100.23,"Snow,Fog"
8737,2012-12-30 01:00:00,-9.4,-10.5,92,9,2.4,100.22,"Snow,Fog"
8738,2012-12-30 02:00:00,-9.3,-10.4,92,9,4.0,100.28,"Snow,Fog"
8739,2012-12-30 03:00:00,-9.1,-10.4,90,11,3.6,100.30,"Snow,Fog"
8740,2012-12-30 04:00:00,-9.3,-10.6,90,13,9.7,100.28,"Snow,Fog"
8741,2012-12-30 05:00:00,-9.1,-10.4,90,11,4.0,100.32,"Snow,Fog"
8742,2012-12-30 06:00:00,-9.3,-10.8,89,17,8.0,100.39,"Snow,Fog"
8767,2012-12-31 07:00:00,-9.3,-11.3,85,0,19.3,101.19,Snow Showers
8768,2012-12-31 08:00:00,-8.6,-10.3,87,4,3.2,101.14,Snow Showers
8769,2012-12-31 09:00:00,-8.1,-9.6,89,4,2.4,101.09,Snow
8770,2012-12-31 10:00:00,-7.4,-8.9,89,4,6.4,101.05,"Snow,Fog"
8771,2012-12-31 11:00:00,-6.7,-7.9,91,9,9.7,100.93,Snow
8772,2012-12-31 12:00:00,-5.8,-7.5,88,4,12.9,100.78,Snow
8773,2012-12-31 13:00:00,-4.6,-6.6,86,4,12.9,100.63,Snow
8774,2012-12-31 14:00:00,-3.4,-5.7,84,6,11.3,100.57,Snow
8775,2012-12-31 15:00:00,-2.3,-4.6,84,9,9.7,100.47,Snow
8776,2012-12-31 16:00:00,-1.4,-4.0,82,13,12.9,100.40,Snow
8777,2012-12-31 17:00:00,-1.1,-3.3,85,19,9.7,100.30,Snow
8778,2012-12-31 18:00:00,-1.3,-3.1,88,17,9.7,100.19,Snow
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [525]:
# Find all instances when 'Wind speed is above 24' and 'Visibility'is 25 .
df[(df['Wind Speed_km/h'] > 24) & (df['Visibility_km']==25)]

KeyError: 'Wind Speed_km/h'

In [ ]:
# Data Manipulation : Gets you desired results
# The true power of the Pandas DataFrame is the ease and flexibility of manipulating data to get your desired results.

# Pandas is best at handling tabular data sets comprising different variable types (integer, float, double, etc.).

# In addition, the pandas library can also be used to perform even the most naive of tasks such as loading data or doing feature engineering on time series data.

In [ ]:
# Selection (Part 1)
# How do you select particular rows/columns from the DataFrame ?

# The DataFrame object supports indexing operations just like the Python list class and the Pandas Series object, but is much faster and more powerful.

# Note that when you extract a single row or column, you get a one-dimensional object as output. That is called a pandas Series. The values on the left are just labels taken from the dataframe index.

# On the other hand, when we extract portions of a pandas dataframe, we get a two-dimensional DataFrame type of object. Something to keep in mind for later.

# How to get the Weather column from the "weather_df" dataframe

In [ ]:
in 46 onwards.